sudo: false

language: node_js
node_js:
  - "14"
  - "12"
  - "10"


install:
  - travis_retry npm install

script:
  - npm run build
  - npm run test

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
